# Generated by Django 5.1.2 on 2024-10-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxLevelFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Box Level 5',
                'verbose_name_plural': 'Boxes Level 5',
            },
        ),
        migrations.CreateModel(
            name='BoxLevelFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name': 'Box Level 4',
                'verbose_name_plural': 'Boxes Level 4',
            },
        ),
        migrations.CreateModel(
            name='BoxLevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Box Level 1',
                'verbose_name_plural': 'Boxes Level 1',
            },
        ),
        migrations.CreateModel(
            name='BoxLevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Box Level 3',
                'verbose_name_plural': 'Boxes Level 3',
            },
        ),
        migrations.CreateModel(
            name='BoxLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Box Level 2',
                'verbose_name_plural': 'Boxes Level 2',
            },
        ),
        migrations.CreateModel(
            name='BoxWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=10)),
                ('box_level_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_words_five', to='boxes.boxlevelfive')),
                ('box_level_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_words_four', to='boxes.boxlevelfour')),
                ('box_level_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_words_one', to='boxes.boxlevelone')),
                ('box_level_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_words_three', to='boxes.boxlevelthree')),
                ('box_level_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_words_two', to='boxes.boxleveltwo')),
            ],
            options={
                'verbose_name': 'Box Word',
                'verbose_name_plural': 'Box Words',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('explain', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='boxes.boxword')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
