# Generated by Django 5.1.2 on 2024-10-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
