# Generated by Django 5.1.2 on 2024-10-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_alter_word_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxword',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
