# Generated by Django 5.1.2 on 2024-10-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxword_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxlevelfive',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlevelfour',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlevelone',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlevelthree',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxleveltwo',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
