# Generated by Django 5.1.2 on 2024-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_boxlevelfive_size_boxlevelfour_size_boxlevelone_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='explain',
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
