# Generated by Django 5.1.2 on 2024-10-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_remove_word_explain_word_definition_word_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxword',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='boxword',
            name='size',
        ),
    ]
