# Generated by Django 5.1.2 on 2024-11-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_remove_boxword_capacity_remove_boxword_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Temp Box',
                'verbose_name_plural': 'Temp Boxes',
            },
        ),
        migrations.AlterField(
            model_name='word',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='boxes.boxword'),
        ),
        migrations.AddField(
            model_name='word',
            name='box_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='boxes.temp'),
        ),
    ]
