# Generated by Django 5.1.2 on 2024-11-05 05:34

from django.db import migrations, models

def create_initial_boxes(apps, schema_editor):
    BoxLevelOne = apps.get_model('boxes', 'BoxLevelOne')
    BoxLevelTwo = apps.get_model('boxes', 'BoxLevelTwo')
    BoxLevelThree = apps.get_model('boxes', 'BoxLevelThree')
    BoxLevelFour = apps.get_model('boxes', 'BoxLevelFour')
    BoxLevelFive = apps.get_model('boxes', 'BoxLevelFive')
    Temp = apps.get_model("boxes", "Temp")

    BoxLevelOne.objects.get_or_create(capacity=1, size=0)
    BoxLevelTwo.objects.get_or_create(capacity=2, size=0)
    BoxLevelThree.objects.get_or_create(capacity=4, size=0)
    BoxLevelFour.objects.get_or_create(capacity=8, size=0)
    BoxLevelFive.objects.get_or_create(capacity=15, size=0)
    Temp.objects.get_or_create()

class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_temp_alter_word_box_word_box_temp'),
    ]

    operations = [
        migrations.RunPython(create_initial_boxes),
    ]
