# Generated by Django 5.1.2 on 2024-11-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_create_initial_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxword',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
